repos:
  - repo: local
    hooks:
      - id: make-quality-backend
        name: Quality check (backend)
        entry: make quality-backend
        language: system
        pass_filenames: false
        files: ^backend/(src|tests)/.*\.py$
