from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_dev_utils.types.datetime

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The trigram operator classes used by generated GIN indexes are extension-owned.
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    op.create_table(
        "files__file_model",
        sa.Column("purpose", sa.Enum("ATTACHMENT", name="file_purpose_enum"), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("relative_path", sa.String(length=2048), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("original_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "orphaned_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(trim(name)) > 0",
            name="files_file_name_trimmed_nonblank_check",
        ),
        sa.CheckConstraint(
            "original_sha256 IS NULL OR char_length(original_sha256) = 64",
            name="files_file_original_sha256_length_check",
        ),
        sa.CheckConstraint(
            "char_length(trim(original_name)) > 0",
            name="files_file_original_name_trimmed_nonblank_check",
        ),
        sa.CheckConstraint(
            "size_bytes >= 0",
            name="files_file_size_non_negative_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "relative_path", name="files_file_namespace_relative_path_uniq"
        ),
    )
    op.create_index(
        "files_file_namespace_orphaned_id_idx",
        "files__file_model",
        ["namespace", "orphaned_at", "id"],
        unique=False,
        postgresql_where=sa.text("orphaned_at IS NOT NULL"),
    )
    op.create_index(
        "files_file_namespace_purpose_original_sha256_idx",
        "files__file_model",
        ["namespace", "purpose", "original_sha256"],
        unique=False,
    )
    op.create_index(
        "files_file_purpose_created_id_idx",
        "files__file_model",
        ["purpose", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "knowledge__knowledge_item_model",
        sa.Column(
            "kind", sa.Enum("DATE", "PERSON", name="knowledge_item_kind_enum"), nullable=False
        ),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(description) <= 100000", name="knowledge_items_description_length_check"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "author_username", name="knowledge_items_id_author_uniq"),
    )
    op.create_index(
        "knowledge_items_author_kind_name_id_idx",
        "knowledge__knowledge_item_model",
        [
            "author_username",
            "kind",
            sa.literal_column("lower(display_name)").label("display_name_lower"),
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "knowledge_items_author_kind_updated_id_idx",
        "knowledge__knowledge_item_model",
        [
            "author_username",
            "kind",
            sa.literal_column("updated_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "knowledge_items_display_name_trgm_idx",
        "knowledge__knowledge_item_model",
        [sa.literal_column("lower(display_name)").label("display_name_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"display_name_lower_trgm": "gin_trgm_ops"},
    )
    op.create_table(
        "knowledge__knowledge_tag_model",
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "author_username", name="knowledge_tags_id_author_uniq"),
    )
    op.create_index(
        "knowledge_tags_author_name_id_idx",
        "knowledge__knowledge_tag_model",
        ["author_username", sa.literal_column("lower(name)").label("name_lower"), "id"],
        unique=False,
    )
    op.create_index(
        "knowledge_tags_author_name_lower_uniq",
        "knowledge__knowledge_tag_model",
        ["author_username", sa.literal_column("lower(name)").label("name_lower")],
        unique=True,
    )
    op.create_index(
        "knowledge_tags_name_trgm_idx",
        "knowledge__knowledge_tag_model",
        [sa.literal_column("lower(name)").label("name_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_lower_trgm": "gin_trgm_ops"},
    )
    op.create_table(
        "knowledge__person_relationship_type_model",
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("is_symmetric", sa.Boolean(), nullable=False),
        sa.Column("forward_name", sa.String(length=255), nullable=False),
        sa.Column("reverse_name", sa.String(length=255), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_symmetric AND char_length(trim(forward_name)) > 0 AND reverse_name = forward_name OR NOT is_symmetric AND char_length(trim(forward_name)) > 0 AND char_length(trim(reverse_name)) > 0",
            name="person_relationship_types_names_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "author_username", name="person_relationship_types_id_author_uniq"
        ),
    )
    op.create_index(
        "person_relationship_types_author_name_id_idx",
        "knowledge__person_relationship_type_model",
        [
            "author_username",
            sa.literal_column("lower(forward_name)").label("forward_name_lower"),
            "id",
        ],
        unique=False,
    )
    op.create_table(
        "resumes__resume_model",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("language", sa.Enum("RU", "EN", name="language_enum"), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "resumes_resume_author_updated_id_idx",
        "resumes__resume_model",
        ["author_username", sa.literal_column("updated_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "knowledge__date_details_model",
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "day BETWEEN 1 AND 31 AND month BETWEEN 1 AND 12 AND (year IS NULL OR year BETWEEN 1 AND 9999) AND day <= CASE WHEN (month IN (1, 3, 5, 7, 8, 10, 12)) THEN 31 WHEN (month IN (4, 6, 9, 11)) THEN 30 WHEN (year IS NULL) THEN 29 WHEN (year % 400 = 0 OR year % 4 = 0 AND year % 100 != 0) THEN 29 ELSE 28 END AND (year IS NULL OR CURRENT_DATE >= make_date(year, month, day))",
            name="date_details_calendar_check",
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "author_username"],
            [
                "knowledge__knowledge_item_model.id",
                "knowledge__knowledge_item_model.author_username",
            ],
            name="date_details_item_author_fk",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id", "author_username", name="date_details_id_author_uniq"),
    )
    op.create_index(
        "date_details_author_calendar_item_idx",
        "knowledge__date_details_model",
        ["author_username", "month", "day", "item_id"],
        unique=False,
    )
    op.create_table(
        "knowledge__knowledge_item_file_model",
        sa.Column("file_id", sa.String(length=32), nullable=False),
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("ATTACHMENT", "PERSON_PHOTO", name="knowledge_file_kind_enum"),
            nullable=False,
        ),
        sa.Column(
            "processing",
            sa.Enum(
                "RAW",
                "NORMALIZED_RASTER_IMAGE",
                name="knowledge_file_processing_enum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files__file_model.id"],
            name="knowledge_item_files_file_fk",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "author_username"],
            [
                "knowledge__knowledge_item_model.id",
                "knowledge__knowledge_item_model.author_username",
            ],
            name="knowledge_item_files_item_author_fk",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_index(
        "knowledge_item_files_author_item_kind_file_idx",
        "knowledge__knowledge_item_file_model",
        ["author_username", "item_id", "kind", "file_id"],
        unique=False,
    )
    op.create_index(
        "knowledge_item_files_one_person_photo_idx",
        "knowledge__knowledge_item_file_model",
        ["author_username", "item_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'PERSON_PHOTO'"),
    )
    op.create_table(
        "knowledge__knowledge_item_tag_model",
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("tag_id", sa.String(length=32), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "author_username"],
            [
                "knowledge__knowledge_item_model.id",
                "knowledge__knowledge_item_model.author_username",
            ],
            name="knowledge_item_tags_item_author_fk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id", "author_username"],
            ["knowledge__knowledge_tag_model.id", "knowledge__knowledge_tag_model.author_username"],
            name="knowledge_item_tags_tag_author_fk",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("item_id", "tag_id"),
    )
    op.create_index(
        "knowledge_item_tags_author_tag_item_idx",
        "knowledge__knowledge_item_tag_model",
        ["author_username", "tag_id", "item_id"],
        unique=False,
    )
    op.create_table(
        "knowledge__person_details_model",
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("middle_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=False),
        sa.Column("telegram", sa.String(length=255), nullable=False),
        sa.Column("birthday_day", sa.Integer(), nullable=True),
        sa.Column("birthday_month", sa.Integer(), nullable=True),
        sa.Column("birthday_year", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "birthday_day IS NULL AND birthday_month IS NULL AND birthday_year IS NULL OR birthday_day IS NOT NULL AND birthday_month IS NOT NULL AND birthday_day BETWEEN 1 AND 31 AND birthday_month BETWEEN 1 AND 12 AND (birthday_year IS NULL OR birthday_year BETWEEN 1 AND 9999) AND birthday_day <= CASE WHEN (birthday_month IN (1, 3, 5, 7, 8, 10, 12)) THEN 31 WHEN (birthday_month IN (4, 6, 9, 11)) THEN 30 WHEN (birthday_year IS NULL) THEN 29 WHEN (birthday_year % 400 = 0 OR birthday_year % 4 = 0 AND birthday_year % 100 != 0) THEN 29 ELSE 28 END AND (birthday_year IS NULL OR CURRENT_DATE >= make_date(birthday_year, birthday_month, birthday_day))",
            name="person_details_birthday_check",
        ),
        sa.CheckConstraint(
            "char_length(trim(last_name)) > 0 AND char_length(trim(first_name)) > 0",
            name="person_details_required_names_check",
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "author_username"],
            [
                "knowledge__knowledge_item_model.id",
                "knowledge__knowledge_item_model.author_username",
            ],
            name="person_details_item_author_fk",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id", "author_username", name="person_details_id_author_uniq"),
    )
    op.create_index(
        "person_details_author_birthday_item_idx",
        "knowledge__person_details_model",
        ["author_username", "birthday_month", "birthday_day", "item_id"],
        unique=False,
    )
    op.create_index(
        "person_details_author_email_item_idx",
        "knowledge__person_details_model",
        ["author_username", sa.literal_column("lower(email)").label("email_lower"), "item_id"],
        unique=False,
    )
    op.create_index(
        "person_details_author_name_search_idx",
        "knowledge__person_details_model",
        [
            "author_username",
            sa.literal_column("lower(last_name)").label("last_name_lower"),
            sa.literal_column("lower(first_name)").label("first_name_lower"),
            "item_id",
        ],
        unique=False,
    )
    op.create_index(
        "person_details_email_trgm_idx",
        "knowledge__person_details_model",
        [sa.literal_column("lower(email)").label("email_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email_lower_trgm": "gin_trgm_ops"},
    )
    op.create_index(
        "person_details_first_name_trgm_idx",
        "knowledge__person_details_model",
        [sa.literal_column("lower(first_name)").label("first_name_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"first_name_lower_trgm": "gin_trgm_ops"},
    )
    op.create_index(
        "person_details_last_name_trgm_idx",
        "knowledge__person_details_model",
        [sa.literal_column("lower(last_name)").label("last_name_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"last_name_lower_trgm": "gin_trgm_ops"},
    )
    op.create_index(
        "person_details_middle_name_trgm_idx",
        "knowledge__person_details_model",
        [sa.literal_column("lower(middle_name)").label("middle_name_lower_trgm")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"middle_name_lower_trgm": "gin_trgm_ops"},
    )
    op.create_table(
        "knowledge__date_person_model",
        sa.Column("date_item_id", sa.String(length=32), nullable=False),
        sa.Column("person_item_id", sa.String(length=32), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["date_item_id", "author_username"],
            [
                "knowledge__date_details_model.item_id",
                "knowledge__date_details_model.author_username",
            ],
            name="date_people_date_author_fk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_item_id", "author_username"],
            [
                "knowledge__person_details_model.item_id",
                "knowledge__person_details_model.author_username",
            ],
            name="date_people_person_author_fk",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("date_item_id", "person_item_id"),
    )
    op.create_index(
        "date_people_author_date_person_idx",
        "knowledge__date_person_model",
        ["author_username", "date_item_id", "person_item_id"],
        unique=False,
    )
    op.create_index(
        "date_people_author_person_date_idx",
        "knowledge__date_person_model",
        ["author_username", "person_item_id", "date_item_id"],
        unique=False,
    )
    op.create_table(
        "knowledge__person_relationship_model",
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("source_person_id", sa.String(length=32), nullable=False),
        sa.Column("target_person_id", sa.String(length=32), nullable=False),
        sa.Column("relationship_type_id", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(note) <= 10000", name="person_relationships_note_length_check"
        ),
        sa.CheckConstraint(
            "source_person_id != target_person_id", name="person_relationships_not_self_check"
        ),
        sa.ForeignKeyConstraint(
            ["relationship_type_id", "author_username"],
            [
                "knowledge__person_relationship_type_model.id",
                "knowledge__person_relationship_type_model.author_username",
            ],
            name="person_relationships_type_author_fk",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_person_id", "author_username"],
            [
                "knowledge__person_details_model.item_id",
                "knowledge__person_details_model.author_username",
            ],
            name="person_relationships_source_author_fk",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_person_id", "author_username"],
            [
                "knowledge__person_details_model.item_id",
                "knowledge__person_details_model.author_username",
            ],
            name="person_relationships_target_author_fk",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "person_relationships_author_pair_type_uniq",
        "knowledge__person_relationship_model",
        [
            "author_username",
            sa.literal_column("least(source_person_id, target_person_id)"),
            sa.literal_column("greatest(source_person_id, target_person_id)"),
            "relationship_type_id",
        ],
        unique=True,
    )
    op.create_index(
        "person_relationships_author_source_idx",
        "knowledge__person_relationship_model",
        ["author_username", "source_person_id", "id"],
        unique=False,
    )
    op.create_index(
        "person_relationships_author_target_idx",
        "knowledge__person_relationship_model",
        ["author_username", "target_person_id", "id"],
        unique=False,
    )
    op.create_index(
        "person_relationships_author_type_id_idx",
        "knowledge__person_relationship_model",
        ["author_username", "relationship_type_id", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "person_relationships_author_type_id_idx", table_name="knowledge__person_relationship_model"
    )
    op.drop_index(
        "person_relationships_author_target_idx", table_name="knowledge__person_relationship_model"
    )
    op.drop_index(
        "person_relationships_author_source_idx", table_name="knowledge__person_relationship_model"
    )
    op.drop_index(
        "person_relationships_author_pair_type_uniq",
        table_name="knowledge__person_relationship_model",
    )
    op.drop_table("knowledge__person_relationship_model")
    op.drop_index("date_people_author_person_date_idx", table_name="knowledge__date_person_model")
    op.drop_index("date_people_author_date_person_idx", table_name="knowledge__date_person_model")
    op.drop_table("knowledge__date_person_model")
    op.drop_index(
        "person_details_middle_name_trgm_idx",
        table_name="knowledge__person_details_model",
        postgresql_using="gin",
        postgresql_ops={"middle_name_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "person_details_last_name_trgm_idx",
        table_name="knowledge__person_details_model",
        postgresql_using="gin",
        postgresql_ops={"last_name_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "person_details_first_name_trgm_idx",
        table_name="knowledge__person_details_model",
        postgresql_using="gin",
        postgresql_ops={"first_name_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "person_details_email_trgm_idx",
        table_name="knowledge__person_details_model",
        postgresql_using="gin",
        postgresql_ops={"email_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "person_details_author_name_search_idx", table_name="knowledge__person_details_model"
    )
    op.drop_index(
        "person_details_author_email_item_idx", table_name="knowledge__person_details_model"
    )
    op.drop_index(
        "person_details_author_birthday_item_idx", table_name="knowledge__person_details_model"
    )
    op.drop_table("knowledge__person_details_model")
    op.drop_index(
        "knowledge_item_tags_author_tag_item_idx", table_name="knowledge__knowledge_item_tag_model"
    )
    op.drop_table("knowledge__knowledge_item_tag_model")
    op.drop_index(
        "knowledge_item_files_one_person_photo_idx",
        table_name="knowledge__knowledge_item_file_model",
        postgresql_where=sa.text("kind = 'PERSON_PHOTO'"),
    )
    op.drop_index(
        "knowledge_item_files_author_item_kind_file_idx",
        table_name="knowledge__knowledge_item_file_model",
    )
    op.drop_table("knowledge__knowledge_item_file_model")
    op.drop_index(
        "date_details_author_calendar_item_idx", table_name="knowledge__date_details_model"
    )
    op.drop_table("knowledge__date_details_model")
    op.drop_index("resumes_resume_author_updated_id_idx", table_name="resumes__resume_model")
    op.drop_table("resumes__resume_model")
    op.drop_index(
        "person_relationship_types_author_name_id_idx",
        table_name="knowledge__person_relationship_type_model",
    )
    op.drop_table("knowledge__person_relationship_type_model")
    op.drop_index(
        "knowledge_tags_name_trgm_idx",
        table_name="knowledge__knowledge_tag_model",
        postgresql_using="gin",
        postgresql_ops={"name_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "knowledge_tags_author_name_lower_uniq", table_name="knowledge__knowledge_tag_model"
    )
    op.drop_index("knowledge_tags_author_name_id_idx", table_name="knowledge__knowledge_tag_model")
    op.drop_table("knowledge__knowledge_tag_model")
    op.drop_index(
        "knowledge_items_display_name_trgm_idx",
        table_name="knowledge__knowledge_item_model",
        postgresql_using="gin",
        postgresql_ops={"display_name_lower_trgm": "gin_trgm_ops"},
    )
    op.drop_index(
        "knowledge_items_author_kind_updated_id_idx", table_name="knowledge__knowledge_item_model"
    )
    op.drop_index(
        "knowledge_items_author_kind_name_id_idx", table_name="knowledge__knowledge_item_model"
    )
    op.drop_table("knowledge__knowledge_item_model")
    op.drop_index("files_file_purpose_created_id_idx", table_name="files__file_model")
    op.drop_index(
        "files_file_namespace_purpose_original_sha256_idx", table_name="files__file_model"
    )
    op.drop_index(
        "files_file_namespace_orphaned_id_idx",
        table_name="files__file_model",
        postgresql_where=sa.text("orphaned_at IS NOT NULL"),
    )
    op.drop_table("files__file_model")
    postgresql.ENUM(name="language_enum", create_type=False).drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="knowledge_file_kind_enum", create_type=False).drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="knowledge_file_processing_enum", create_type=False).drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="knowledge_item_kind_enum", create_type=False).drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="file_purpose_enum", create_type=False).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
