from alembic import op
import sqlalchemy as sa
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram__telegram_connection_model",
        sa.Column("owner_username", sa.String(length=255), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("private_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING", "ACTIVE", "REVOKED", "BLOCKED", name="telegram_connection_state_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "connected_at",
            UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "state_changed_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_contact_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telegram__telegram_connection_model_owner_username"),
        "telegram__telegram_connection_model",
        ["owner_username"],
        unique=False,
    )
    op.create_index(
        "telegram_connection_active_user_uidx",
        "telegram__telegram_connection_model",
        ["telegram_user_id"],
        unique=True,
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    op.create_index(
        "telegram_connection_live_owner_user_uidx",
        "telegram__telegram_connection_model",
        ["owner_username", "telegram_user_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('PENDING', 'ACTIVE', 'BLOCKED')"),
    )
    op.create_table(
        "telegram__telegram_invitation_model",
        sa.Column("owner_username", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "used_at", UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "cancelled_at",
            UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_telegram__telegram_invitation_model_owner_username"),
        "telegram__telegram_invitation_model",
        ["owner_username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram__telegram_invitation_model_owner_username"),
        table_name="telegram__telegram_invitation_model",
    )
    op.drop_table("telegram__telegram_invitation_model")
    op.drop_index(
        "telegram_connection_live_owner_user_uidx",
        table_name="telegram__telegram_connection_model",
        postgresql_where=sa.text("state IN ('PENDING', 'ACTIVE', 'BLOCKED')"),
    )
    op.drop_index(
        "telegram_connection_active_user_uidx",
        table_name="telegram__telegram_connection_model",
        postgresql_where=sa.text("state = 'ACTIVE'"),
    )
    op.drop_index(
        op.f("ix_telegram__telegram_connection_model_owner_username"),
        table_name="telegram__telegram_connection_model",
    )
    op.drop_table("telegram__telegram_connection_model")
    sa.Enum(
        "PENDING",
        "ACTIVE",
        "REVOKED",
        "BLOCKED",
        name="telegram_connection_state_enum",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
