from alembic import op
import sqlalchemy as sa
from sqlalchemy_dev_utils.types.datetime import UTCDateTime


revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("RU", "EN", name="telegram_notification_language_enum").create(
        op.get_bind(), checkfirst=True
    )
    op.create_table(
        "notifications__reminder_delivery_model",
        sa.Column("connection_id", sa.String(length=32), nullable=False),
        sa.Column(
            "kind", sa.Enum("BIRTHDAY", "MEMORABLE_DATE", name="reminder_kind_enum"), nullable=False
        ),
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("lead_days", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "RETRY",
                "DONE",
                "CANCELED",
                "EXPIRED",
                "FAILED",
                name="reminder_delivery_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "claimed_until",
            UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "next_attempt_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("expires_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "sent_at", UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "kind",
            "item_id",
            "occurrence_date",
            "lead_days",
            name="reminder_delivery_once_uniq",
        ),
    )
    op.create_index(
        "reminder_delivery_status_retry_idx",
        "notifications__reminder_delivery_model",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.add_column(
        "knowledge__date_details_model",
        sa.Column("notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "knowledge__person_details_model",
        sa.Column("notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "telegram__telegram_connection_model",
        sa.Column("notify_birthday", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "telegram__telegram_connection_model",
        sa.Column("notify_memorable_date", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "telegram__telegram_connection_model",
        sa.Column(
            "language",
            sa.Enum("RU", "EN", name="telegram_notification_language_enum"),
            server_default="EN",
            nullable=False,
        ),
    )
    op.add_column(
        "telegram__telegram_connection_model",
        sa.Column("time_zone", sa.String(length=64), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram__telegram_connection_model", "time_zone")
    op.drop_column("telegram__telegram_connection_model", "language")
    op.drop_column("telegram__telegram_connection_model", "notify_memorable_date")
    op.drop_column("telegram__telegram_connection_model", "notify_birthday")
    op.drop_column("knowledge__person_details_model", "notifications_enabled")
    op.drop_column("knowledge__date_details_model", "notifications_enabled")
    op.drop_index(
        "reminder_delivery_status_retry_idx", table_name="notifications__reminder_delivery_model"
    )
    op.drop_table("notifications__reminder_delivery_model")
    sa.Enum("RU", "EN", name="telegram_notification_language_enum").drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum("PENDING", "IN_PROGRESS", "RETRY", "DONE", "CANCELED", "EXPIRED", "FAILED", name="reminder_delivery_status_enum").drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum("BIRTHDAY", "MEMORABLE_DATE", name="reminder_kind_enum").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
