from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_dev_utils.types.datetime

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finance_rate_set",
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("effective_on", sa.Date(), nullable=False),
        sa.Column(
            "fetched_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "effective_on", "payload_hash"),
    )
    op.create_table(
        "finance_template_category",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.Enum("INCOME", "EXPENSE", name="finance_kind_enum"), nullable=False),
        sa.Column("name_ru", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "finance_tracker",
        sa.Column("owner_username", sa.String(length=255), nullable=False),
        sa.Column("timezone_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_username"),
    )
    op.create_table(
        "finance_category",
        sa.Column("tracker_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.Enum("INCOME", "EXPENSE", name="finance_kind_enum"), nullable=False),
        sa.Column(
            "archived_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tracker_id"], ["finance_tracker.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finance_month",
        sa.Column("tracker_id", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("AMD", "RUB", "USD", "EUR", name="finance_currency_enum"),
            nullable=False,
        ),
        sa.Column("opening_balance", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("previous_month_id", sa.String(length=32), nullable=True),
        sa.Column("transferred_balance", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["previous_month_id"],
            ["finance_month.id"],
        ),
        sa.ForeignKeyConstraint(["tracker_id"], ["finance_tracker.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracker_id", "period_start"),
    )
    op.create_table(
        "finance_rate",
        sa.Column("rate_set_id", sa.String(length=32), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("AMD", "RUB", "USD", "EUR", name="finance_currency_enum"),
            nullable=False,
        ),
        sa.Column("nominal", sa.Integer(), nullable=False),
        sa.Column("rub_per_unit", sa.Numeric(precision=30, scale=18), nullable=False),
        sa.ForeignKeyConstraint(["rate_set_id"], ["finance_rate_set.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rate_set_id", "currency"),
    )
    op.create_table(
        "finance_month_category",
        sa.Column("month_id", sa.String(length=32), nullable=False),
        sa.Column("category_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.Enum("INCOME", "EXPENSE", name="finance_kind_enum"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("planned_amount", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("accepting_transactions", sa.Boolean(), nullable=False),
        sa.Column("source_month_category_id", sa.String(length=32), nullable=True),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["finance_category.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["month_id"], ["finance_month.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_month_category_id"],
            ["finance_month_category.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month_id", "category_id"),
        sa.UniqueConstraint("month_id", "kind", "normalized_name"),
    )
    op.create_index(
        "finance_month_category_order_idx",
        "finance_month_category",
        ["month_id", "kind", "position"],
        unique=False,
    )
    op.create_table(
        "finance_month_currency_change",
        sa.Column("month_id", sa.String(length=32), nullable=False),
        sa.Column(
            "previous_currency",
            sa.Enum("AMD", "RUB", "USD", "EUR", name="finance_currency_enum"),
            nullable=False,
        ),
        sa.Column(
            "new_currency",
            sa.Enum("AMD", "RUB", "USD", "EUR", name="finance_currency_enum"),
            nullable=False,
        ),
        sa.Column("rate_set_id", sa.String(length=32), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_username", sa.String(length=255), nullable=False),
        sa.Column(
            "changed_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["month_id"],
            ["finance_month.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rate_set_id"],
            ["finance_rate_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finance_transaction",
        sa.Column("month_id", sa.String(length=32), nullable=False),
        sa.Column("month_category_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.Enum("INCOME", "EXPENSE", name="finance_kind_enum"), nullable=False),
        sa.Column("original_amount", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column(
            "original_currency",
            sa.Enum("AMD", "RUB", "USD", "EUR", name="finance_currency_enum"),
            nullable=False,
        ),
        sa.Column("amount_rub", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("rate_set_id", sa.String(length=32), nullable=False),
        sa.Column(
            "occurred_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("author_username", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "deleted_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["month_category_id"],
            ["finance_month_category.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["month_id"],
            ["finance_month.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rate_set_id"],
            ["finance_rate_set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "finance_transaction_month_date_idx",
        "finance_transaction",
        ["month_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "finance_transaction_revision",
        sa.Column("transaction_id", sa.String(length=32), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("UPDATE", "DELETE", "RESTORE", name="finance_revision_action_enum"),
            nullable=False,
        ),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor_username", sa.String(length=255), nullable=False),
        sa.Column(
            "changed_at",
            sqlalchemy_dev_utils.types.datetime.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.String(length=32),
            server_default=sa.text("replace(CAST(gen_random_uuid() AS VARCHAR), '-', '')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["transaction_id"], ["finance_transaction.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id", "number"),
    )
    template = sa.table(
        "finance_template_category",
        sa.column("key", sa.String(80)),
        sa.column("kind", sa.Enum("INCOME", "EXPENSE", name="finance_kind_enum")),
        sa.column("name_ru", sa.String(255)),
        sa.column("name_en", sa.String(255)),
        sa.column("position", sa.Integer()),
    )
    expense_names = [
        ("food", "Еда", "Food"),
        ("gifts", "Подарки", "Gifts"),
        ("health", "Здоровье", "Health"),
        ("beauty", "Красота", "Beauty"),
        ("transport", "Транспорт", "Transport"),
        ("car", "Автомобиль", "Car"),
        ("sports", "Спорт", "Sports"),
        ("housing", "Жильё", "Housing"),
        ("dining", "Рестораны и доставка", "Dining and delivery"),
        ("clothing", "Одежда", "Clothing"),
        ("work", "Работа", "Work"),
        ("misc", "Разное", "Miscellaneous"),
        ("subscriptions", "Подписки", "Subscriptions"),
        ("education", "Образование", "Education"),
        ("major_purchases", "Крупные покупки", "Major purchases"),
        ("home", "Дом", "Home"),
    ]
    income_names = [
        ("salary", "Зарплата", "Salary"),
        ("bonus", "Премия", "Bonus"),
        ("interest", "Проценты", "Interest income"),
        ("personal_sales", "Продажа вещей", "Sales of personal items"),
        ("other_income", "Другое", "Other"),
    ]
    op.bulk_insert(template, [
        {"key": key, "kind": kind, "name_ru": name_ru,
         "name_en": name_en, "position": position}
        for kind, names in (("EXPENSE", expense_names), ("INCOME", income_names))
        for position, (key, name_ru, name_en) in enumerate(names)
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finance_transaction_revision")
    op.drop_index("finance_transaction_month_date_idx", table_name="finance_transaction")
    op.drop_table("finance_transaction")
    op.drop_table("finance_month_currency_change")
    op.drop_index("finance_month_category_order_idx", table_name="finance_month_category")
    op.drop_table("finance_month_category")
    op.drop_table("finance_rate")
    op.drop_table("finance_month")
    op.drop_table("finance_category")
    op.drop_table("finance_tracker")
    op.drop_table("finance_template_category")
    op.drop_table("finance_rate_set")
    postgresql.ENUM(name="finance_revision_action_enum", create_type=False).drop(
        op.get_bind(), checkfirst=True,
    )
    postgresql.ENUM(name="finance_kind_enum", create_type=False).drop(
        op.get_bind(), checkfirst=True,
    )
    postgresql.ENUM(name="finance_currency_enum", create_type=False).drop(
        op.get_bind(), checkfirst=True,
    )
    # ### end Alembic commands ###
