from .base import BaseModel as BaseModel
from .events import EventModel as EventModel
from .files import FileModel as FileModel
from .finance import FinanceCategoryModel as FinanceCategoryModel
from .finance import FinanceMonthCategoryModel as FinanceMonthCategoryModel
from .finance import FinanceMonthCurrencyChangeModel as FinanceMonthCurrencyChangeModel
from .finance import FinanceMonthModel as FinanceMonthModel
from .finance import FinanceRateModel as FinanceRateModel
from .finance import FinanceRateSetModel as FinanceRateSetModel
from .finance import FinanceTemplateCategoryModel as FinanceTemplateCategoryModel
from .finance import FinanceTrackerModel as FinanceTrackerModel
from .finance import FinanceTransactionModel as FinanceTransactionModel
from .finance import FinanceTransactionRevisionModel as FinanceTransactionRevisionModel
from .finance_notifications import FinanceDeliveryModel as FinanceDeliveryModel
from .finance_notifications import FinanceEventModel as FinanceEventModel
from .important_info import ImportantInfoModel as ImportantInfoModel
from .knowledge import KnowledgeDateDetailsModel as KnowledgeDateDetailsModel
from .knowledge import KnowledgeDatePersonModel as KnowledgeDatePersonModel
from .knowledge import KnowledgeItemFileModel as KnowledgeItemFileModel
from .knowledge import KnowledgeItemModel as KnowledgeItemModel
from .knowledge import KnowledgeItemTagModel as KnowledgeItemTagModel
from .knowledge import KnowledgeTagModel as KnowledgeTagModel
from .knowledge import PersonDetailsModel as PersonDetailsModel
from .knowledge import PersonRelationshipModel as PersonRelationshipModel
from .knowledge import PersonRelationshipTypeModel as PersonRelationshipTypeModel
from .notifications import ReminderDeliveryModel as ReminderDeliveryModel
from .resumes import ResumeModel as ResumeModel
from .telegram import TelegramConnectionModel as TelegramConnectionModel
from .telegram import TelegramInvitationModel as TelegramInvitationModel
from .vault import VaultEntryModel as VaultEntryModel

BaseModel.registry.configure()
