name: Backend tests

on:
  workflow_call:

jobs:
  backend-tests:
    name: Backend tests
    timeout-minutes: 60
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    services:
      postgres:
        image: postgres:18.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: personal_workspace_database_test
        options: >-
          --health-cmd "pg_isready -U postgres -d personal_workspace_database_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 55432:5432
    steps:
      - uses: actions/checkout@v7
      - name: "Set up Python"
        uses: actions/setup-python@v7
        with:
          python-version-file: "backend/pyproject.toml"
      - name: "Install UV"
        uses: astral-sh/setup-uv@v10.1.0
        with:
          cache-suffix: "backend-tests"
      - name: "Run backend tests with coverage"
        run: make tests-coverage
      - name: "Coverage Badge"
        run: |
          pip install -U genbadge defusedxml
          genbadge coverage -n backend -i backend/coverage.xml -o .github/badges/coverage-backend.svg
      - name: "Verify Changed files"
        id: verify-changed-files
        run: |
          if git diff --quiet -- .github/badges/coverage-backend.svg; then
            echo "files_changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "files_changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: "Commit and push badge"
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && steps.verify-changed-files.outputs.files_changed == 'true'
        uses: EndBug/add-and-commit@v11
        with:
          add: '.github/badges/coverage-backend.svg'
          message: 'Updated .github/badges/coverage-backend.svg - project coverage have changed'
          pull: '--rebase --autostash'
          default_author: github_actions
