name: Backend pip-audit

on:
  workflow_call:

jobs:
  backend-pip-audit:
    name: Backend pip-audit
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
      - name: "Set up Python"
        uses: actions/setup-python@v7
        with:
          python-version-file: "backend/pyproject.toml"
      - name: "Install UV"
        uses: astral-sh/setup-uv@v10.1.0
        with:
          cache-suffix: "backend-pip-audit"
      - name: "pip-audit"
        run: make -C backend security-pip-audit
